
name: CI

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
        - master
        - develop 

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: 13.x
    - run: npm install
      working-directory: ./server
    - name: Run tests
    - run: npm test
      working-directory: ./server
        
